<?php
namespace Application\Controllers;
use Application\Core\User;
use Phalcon\Mvc\View;

class IndexController extends ControllerBase {
	public function beforeExecuteRoute($dispatcher)
    {
        parent::beforeExecuteRoute($dispatcher); // TODO: Change the autogenerated stub
    }
    
    public function indexAction() {
		$this->view->disable();
		echo "<h1>Ayam<h1>";
    }

}